name: Test action
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ftp setup
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{secrets.HOST}}
          user: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          localDir: "/home/runner/work/keep_note/keep_note/myapp"
          remoteDir: "public_html"
