name: Keep-note action
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{secrets.HOST}}
          user: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          localDir: "myapp"
          remoteDir: "public_html"
